var expect = require('chai').expect;
var Plugin = require('./');
var header = '// Generated by EmberScript 0.0.14\n';

describe('Plugin', function() {
  var plugin;

  beforeEach(function() {
    plugin = new Plugin({});
  });

  it('should be an object', function() {
    expect(plugin).to.be.ok;
  });

  it('should has #compile method', function() {
    expect(plugin.compile).to.be.an.instanceof(Function);
  });

  it('should compile and produce valid result', function(done) {
    var content = 'a = 1';
    var expected = header + 'var a;\na = 1;';

    plugin.compile(content, 'file.em', function(error, data) {
      expect(error).not.to.be.ok;
      expect(data.data).to.equal(expected);
      done();
    });
  });

  it('should produce source maps', function(done) {
    plugin = new Plugin({sourceMaps: true});

    var content = 'a = 1';
    var expected = header + 'var a;\na = 1;';

    plugin.compile(content, 'file.em', function(error, data) {
      expect(error).not.to.be.ok;
      expect(data.data).to.equal(expected);
      expect(data.map).to.be.a('string');
      done();
    });
  });

  it('should support explicit bare setting', function(done) {
    plugin = new Plugin({plugins:{emberscript:{bare:false}}});

    var content = 'a = 1';
    var expected = header + 'void function () {\n  var a;\n  a = 1;\n}.call(this);';

    plugin.compile(content, 'file.em', function(error, data) {
      expect(error).not.to.be.ok;
      expect(data.data).to.equal(expected);

      plugin = new Plugin({plugins:{emberscript:{bare:true}}});
      content = 'a = 1';
      expected = header + 'var a;\na = 1;';

      plugin.compile(content, 'file.em', function(error, data) {
        expect(error).not.to.be.ok;
        expect(data.data).to.equal(expected);
        done();
      });
    });
  });
});
